export const FACEBOOK_LOGIN = 'FACEBOOK_LOGIN'

export const TAP_MESSAGE = 'TAP_MESSAGE'

export const LIKE_RECIPE = 'LIKE_RECIPE'
export const BOOKMARK_RECIPE = 'BOOKMARK_RECIPE'

export const EXPLORE_MORE_RECIPE = 'EXPLORE_MORE_RECIPE'